routes/web.php
<?php
Route::get('test','Controller@test');

Route::group(['middleware' => 'CheckKeToan'],function(){

	Route::group(['prefix' => 'muc_luong', 'as' => 'muc_luong.'],function(){
		Route::get('','LuongController@view_all')->name('view_all');
		Route::get('view_insert','LuongController@view_insert')->name('view_insert');
		Route::post('process_insert','LuongController@process_insert')->name('process_insert');


		Route::get('view_update/{ma_muc_luong}','LuongController@view_update')->name('view_update');
		Route::post('process_update/{ma_muc_luong}','LuongController@process_update')->name('process_update');
	});
	?>

	<?php

	Route::group(['prefix' => 'ke_toan', 'as' => 'ke_toan.'],function(){
		Route::get('','Ke_toanController@view_all')->name('view_all_ke_toan');
		Route::get('view_insert','Ke_toanController@view_insert')->name('view_insert_ke_toan');
		Route::post('process_insert','Ke_toanController@process_insert')->name('process_insert');

		Route::get('view_update/{ma_ke_toan}','Ke_toanController@view_update')->name('view_update_ke_toan');
		Route::post('process_update/{ma_ke_toan}','Ke_toanController@process_update')->name('process_update');
	});

});

Route::group(['middleware' => 'CheckGiaoVien'],function(){

	Route::group(['prefix' => 'giao_vien', 'as' => 'giao_vien.'],function(){
		Route::get('','GiaoVienController@view_all')->name('view_all');
		Route::get('view_insert','GiaoVienController@view_insert')->name('view_insert');
		Route::post('process_insert','GiaoVienController@process_insert')->name('process_insert');


		Route::get('view_update/{ma_giao_vien}','GiaoVienController@view_update')->name('view_update');
		Route::post('process_update/{ma_giao_vien}','GiaoVienController@process_update')->name('process_update');
	});	
});

Route::get('login','Controller@login')->name('view_login');
Route::post('process_login','Controller@process_login')->name('process_login');

Route::get('logout','Controller@logout')->name('logout');
?>

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

use Illuminate\Http\Request;
use App\Model\Ke_toanModel;
use App\Model\GiaoVienModel;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    public function test()
    {
        return view('layer.master');
    }
    public function login()
    {
        return view('login');
    }
    public function process_login(Request $rq)
    {
        $ke_toan           = new Ke_toanModel();
        $ke_toan->email    = $rq->get('email');
        $ke_toan->mat_khau = $rq->get('mat_khau');
        $array             = $ke_toan->get_login();


        if(count($array)==1){
            $rq->session()->put('ma_ke_toan',$array[0]->ma_ke_toan);
            $rq->session()->put('ten_ke_toan',$array[0]->ten_ke_toan);

            return redirect()->route('ke_toan.view_all_ke_toan');
        }
        else{
            $giao_vien         = new GiaoVienModel();
            $giao_vien->email    = $rq->get('email');
            $giao_vien->mat_khau = $rq->get('mat_khau');
            $array           = $giao_vien->get_login();

            if(count($array)==1){
                $rq->session()->put('ma_giao_vien',$array[0]->ma_giao_vien);
                $rq->session()->put('ten_giao_vien',$array[0]->ten_giao_vien);

                return redirect()->route('giao_vien.view_all');
            }
        }
        
        return redirect()->route('view_login')->with('error','Nhập sai rồi');
    }


        public function logout(Request $rq)
    {
        $rq->session()->flush();
        return redirect()->route('view_login')->with('success','Đăng xuất thành công');
    }
}

app/Http/Controllers/GiaoVienController.php
<?php

namespace App\Http\Controllers;

use App\Model\GiaoVienModel;
use Illuminate\Http\Request;

class GiaoVienController
{
	function view_all(){
		$array = GiaoVienModel::get_all();
		
		return view('giao_vien.view_all',compact('array'));
	}
	function view_insert(){
		return view('giao_vien.view_insert');
	}
	function process_insert(Request $rq){
		$giao_vien = new GiaoVienModel();
		$giao_vien->ten_giao_vien = $rq->get('ten_giao_vien');
		$giao_vien->gioi_tinh = $rq->get('gioi_tinh');
		$giao_vien->ngay_sinh = $rq->get('ngay_sinh');
		$giao_vien->email = $rq->get('email');
		$giao_vien->mat_khau = $rq->get('mat_khau');
		$giao_vien->dia_chi = $rq->get('dia_chi');
		
		$giao_vien->insert();

		return redirect()->route('giao_vien.view_all');
	}
	function view_update($ma_giao_vien){
			$each=GiaoVienModel::get_one($ma_giao_vien);
				return view('view_update',compact('each'));
	}
	function process_update(Request $rq){
		$giao_vien = new GiaoVienModel();
		$giao_vien->ten_giao_vien = $rq->get('ten_giao_vien');
		$giao_vien->gioi_tinh = $rq->get('gioi_tinh');
		$giao_vien->ngay_sinh = $rq->get('ngay_sinh');
		$giao_vien->email = $rq->get('email');
		$giao_vien->mat_khau = $rq->get('mat_khau');
		$giao_vien->dia_chi = $rq->get('dia_chi');
		
		$giao_vien->update();

		//return redirect()->route('giao_vien.view_all');
	}
}

app/Http/Controllers/Ke_toanController.php
<?php
namespace App\Http\Controllers;

use App\Model\Ke_toanModel;
use Illuminate\Http\Request;
class Ke_toanController
{
	function view_all(){
		$array = Ke_toanModel::get_all();
		return view('view_all_ke_toan',compact('array'));
	}
	function view_insert(){
		return view('view_insert_ke_toan');
	}
	function process_insert(Request $rq){
		$ke_toan = new Ke_toanModel();
		$ke_toan->ten_ke_toan = $rq ->get('ten_ke_toan');
		$ke_toan->gioi_tinh = $rq ->get('gioi_tinh');
		$ke_toan->ngay_sinh = $rq ->get('ngay_sinh');
		$ke_toan->email = $rq ->get('email');
		$ke_toan->mat_khau = $rq ->get('mat_khau');
		$ke_toan->dia_chi = $rq ->get('dia_chi');
		$ke_toan->insert();
		return redirect()->route('view_all_ke_toan');
	} 
	function view_update($ma_ke_toan)
	{
		$each = Ke_toanModel::get_one($ma_ke_toan);

		return view('view_update_ke_toan',compact('each'));
	}
	function process_update($ma_ke_toan, Request $rq)
	{
		$ke_toan = new Ke_toanModel();
		$ke_toan->ma_ke_toan = $ma_ke_toan;
		$ke_toan->ten_ke_toan = $rq ->get('ten_ke_toan');
		$ke_toan->gioi_tinh = $rq ->get('gioi_tinh');
		$ke_toan->ngay_sinh = $rq ->get('ngay_sinh');
		$ke_toan->email = $rq ->get('email');
		$ke_toan->mat_khau = $rq ->get('mat_khau');
		$ke_toan->dia_chi = $rq ->get('dia_chi');


		$ke_toan->update();

		return redirect()->route("ke_toan.view_all_ke_toan");
	}

}

app/Http/Controllers/LuongController.php
<?php
namespace App\Http\Controllers;

use App\Model\LuongModel;
use Illuminate\Http\Request;
class LuongController
{
	function view_all(){
		$array = LuongModel::get_all();
		return view('view_all',compact('array'));
	}
	function view_insert(){
		return view('view_insert');
	}
	function process_insert(Request $rq){
		$muc_luong = new LuongModel();
		$muc_luong->so_tien_tren_1_gio = $rq ->get('so_tien_tren_1_gio');
		$muc_luong->insert();
		return redirect()->route('muc_luong.view_all');
	} 
	function view_update($ma_muc_luong)
	{
		$each = LuongModel::get_one($ma_muc_luong);

		return view('view_update',compact('each'));
	}
	function process_update($ma_muc_luong, Request $rq)
	{
		$muc_luong = new LuongModel();
		$muc_luong->ma_muc_luong = $ma_muc_luong;
		$muc_luong->so_tien_tren_1_gio = $rq->get('so_tien_tren_1_gio');

		$muc_luong->update();

		return redirect()->route("muc_luong.view_all");
	}
}

resources/views/cham_cong/view_all.blade.php
@extends('layer.master')
@section('body')
<body>
<a href="{{ route('giao_vien.view_insert') }}">
	Thêm
</a>
<table border="1" width="100%">
	<tr>
		<th>Mã giáo viên</th>
		<th>Tên giáo viên</th>
		<th>Giới tính</th>
		<th>Ngày sinh</th>
		<th>Email</th>
		<th>Mật khẩu</th>
		<th>Địa chỉ</th>
		<th>Sửa</th>
	</tr>
	@foreach ($array as $each)
		<tr>
			<td>{{$each->ma_giao_vien}}</td>
			<td>{{$each->ten_giao_vien}}</td>
			<td>
				@if ($each->gioi_tinh==1)
					Nam
				@else
					Nữ
				@endif
			</td>
			<td>{{$each->ngay_sinh}}</td>
			<td>{{$each->email}}</td>
			<td>{{$each->mat_khau}}</td>
			<td>{{$each->dia_chi}}</td>
			<td>
				<a href="{{ route('giao_vien.view_update',['ma_giao_vien' => $each->ma_giao_vien]) }}">
					<button>Sửa</button>
				</a>
			</td>

		</tr>
	@endforeach
</table>
@endsection

resources/views/cham_cong/view_insert.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="{{ route('cham_cong.process_insert')}}" method="post">
	{{csrf_field()}}
	Ngày 
	<input type="text" name="ngay">
	Mã giáo viên
	<input type="text" name="ma_giao_vien">
	<br>
	Số giờ dạy
	<input type="text" name="so_gio_day">
	<br>
	<button>Thêm</button>
</form>
</body>
</html>

resources/views/giao_vien/view_all.blade.php
@extends('layer.master')
@section('body')
<body>
<a href="{{ route('giao_vien.view_insert') }}">
	Thêm
</a>
<table border="1" width="100%">
	<tr>
		<th>Mã giáo viên</th>
		<th>Tên giáo viên</th>
		<th>Giới tính</th>
		<th>Ngày sinh</th>
		<th>Email</th>
		<th>Mật khẩu</th>
		<th>Địa chỉ</th>
		<th>Sửa</th>
	</tr>
	@foreach ($array as $each)
		<tr>
			<td>{{$each->ma_giao_vien}}</td>
			<td>{{$each->ten_giao_vien}}</td>
			<td>
				@if ($each->gioi_tinh==1)
					Nam
				@else
					Nữ
				@endif
			</td>
			<td>{{$each->ngay_sinh}}</td>
			<td>{{$each->email}}</td>
			<td>{{$each->mat_khau}}</td>
			<td>{{$each->dia_chi}}</td>
			<td>
				<a href="{{ route('giao_vien.view_update',['ma_giao_vien' => $each->ma_giao_vien]) }}">
					<button>Sửa</button>
				</a>
			</td>

		</tr>
	@endforeach
</table>
@endsection

resources/views/giao_vien/view_insert.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="{{ route('giao_vien.process_insert')}}" method="post">
	{{csrf_field()}}
	Tên giáo viên
	<input type="text" name="ten_giao_vien">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1">Nam
	<input type="radio" name="gioi_tinh" value="0">Nữ
	<br>
	Ngày sinh
	<input type="text" name="ngay_sinh">
	<br>
	Email
	<input type="email" name="email">
	<br>
	Mật khẩu
	<input type="password" name="mat_khau">
	<br>
	Địa chỉ
	<input type="text" name="dia_chi">
	<br>
	<button>Thêm</button>
</form>
</body>
</html>

resources/views/giao_vien/view_update.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
</head>
<body>
<form action="{{ route('giao_vien.process_update',['ma_giao_vien'=> $each->ma_giao_vien]) }}" method="post">
	{{csrf_field()}}
	Tên giáo viên
	<input type="text" name="ten_giao_vien" value="{{$each->ten_giao_vien}}">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1 {{$each->gioi_tinh}}">Nam
	<input type="radio" name="gioi_tinh" value="0{{$each->gioi_tinh}}">Nữ
	<br>
	Ngày sinh
	<input type="text" name="ngay_sinh" value="{{$each->ngay_sinh}}">
	<br>
	Email
	<input type="email" name="email"value="{{$each->email}}">
	<br>
	Mật khẩu
	<input type="password" name="mat_khau"value="{{$each->mat_khau}}">
	<br>
	Địa chỉ
	<input type="text" name="dia_chi"value="{{$each->dia_chi}}">
	<br>
	<button>OK</button>
</form>
</body>
</html>

resources/views/ke_toan/view_all_ke_toan.blade.php
@extends('layer.master')
@section('body')
<body>
<a href="{{ route('ke_toan.view_insert_ke_toan') }}"> Thêm</a>
<table border="1" width="100%">
	<tr>
		<th>
			Mã
		</th>
		<th>
			Tên
		</th>
		<th>
			Giới Tính
		</th>
			<th>
			Ngày Sinh
		</th>
		<th>
			Email
		</th>
		<th>
			Mật Khẩu
		</th>
		<th>
			Địa Chỉ
		</th>
		<th>
			Sửa
		</th>
	</tr>
	@foreach($array as $each)
	<tr>
		<td>
			{{$each->ma_ke_toan}}

		</td>
		<td>
			{{$each->ten_ke_toan}}
		</td>
		<td>
			@if ($each->gioi_tinh==1) Nam
			@else
			Nữ
			@endif
		</td>
			<td>
			{{$each->ngay_sinh}}

		</td>
		<td>
			{{$each->email}}
		</td
		><td>
			{{$each->mat_khau}}

		</td>
		<td>
			{{$each->dia_chi}}
		</td>
		<td>
		<a href="{{ route('ke_toan.view_update_ke_toan',['ma_ke_toan' => $each->ma_ke_toan]) }}">
			<button>Sửa</button>
		</a>
		</td>
	</tr>
	@endforeach
</table>
@endsection

resources/views/ke_toan/view_insert_ke_toan.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<form action="{{ route('ke_toan.process_insert')}}" method="post">
	{{csrf_field()}}
	Tên Kế Toán
	<input type="text" name="ten_ke_toan">
	<br>
	Giới tính
	<input type="radio" name="gioi_tinh" value="1">Nam
	<input type="radio" name="gioi_tinh" value="0">Nữ
	<br>
	Ngày sinh
	<input type="date" name="ngay_sinh">
	<br>
	Email
	<input type="email" name="email">
	<br>
	Mật khẩu
	<input type="password" name="mat_khau">
	<br>
	Địa chỉ
	<input type="text" name="dia_chi">
	<br>
	<button>Thêm</button>
</form>
</body>
</html>

resources/views/ke_toan/view_update_ke_toan.blade.php
@extends('layer.master')
@section('body')
<body>
	<form action="{{ route('ke_toan.process_update',['ma_ke_toan' => $each->ma_ke_toan]) }}" method="post">
		{{csrf_field()}}
		Tên Kế Toán
		<input type="text" name="ten_ke_toan" value="{{$each->ten_ke_toan}}">
		<br>
		Giới tính
		<input type="radio" name="gioi_tinh" value="1{{$each->gioi_tinh}}">Nam
		<input type="radio" name="gioi_tinh" value="0{{$each->gioi_tinh}}">Nữ
		<br>
		Ngày sinh
		<input type="text" name="ngay_sinh" value="{{$each->ngay_sinh}}">
		<br>
		Email
		<input type="email" name="email" value="{{$each->email}}">
		<br>
		Mật khẩu
		<input type="password" name="mat_khau" value="{{$each->mat_khau}}">
		<br>
		Địa chỉ
		<input type="text" name="dia_chi" value="{{$each->dia_chi}}">
		<br>
			<button>Sửa</button>
	</form>
</body>
@endsection

resources/views/layer/footer.blade.php
 <footer class="footer">
    <div class="container-fluid">
        <nav class="pull-left">
            <ul>
                <li>
                    <a href="#">
                        Home
                    </a>
                </li>
                <li>
                    <a href="#">
                        Company
                    </a>
                </li>
                <li>
                    <a href="#">
                        Portfolio
                    </a>
                </li>
                <li>
                    <a href="#">
                       Blog
                    </a>
                </li>
            </ul>
        </nav>
        <p class="copyright pull-right">
            &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
        </p>
    </div>
</footer>

resources/views/layer/header.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
		<div class="navbar-minimize">
			<button id="minimizeSidebar" class="btn btn-warning btn-fill btn-round btn-icon">
				<i class="fa fa-ellipsis-v visible-on-sidebar-regular"></i>
				<i class="fa fa-navicon visible-on-sidebar-mini"></i>
			</button>
		</div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Calendar</a>
        </div>
        <div class="collapse navbar-collapse">

            <form class="navbar-form navbar-left navbar-search-form" role="search">
                <div class="input-group">
                    <span class="input-group-addon"><i class="fa fa-search"></i></span>
                    <input type="text" value="" class="form-control" placeholder="Search...">
                </div>
            </form>

            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="charts.html">
                        <i class="fa fa-line-chart"></i>
                        <p>Stats</p>
                    </a>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-gavel"></i>
                        <p class="hidden-md hidden-lg">
                            Actions
                            <b class="caret"></b>
                        </p>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Create New Post</a></li>
                        <li><a href="#">Manage Something</a></li>
                        <li><a href="#">Do Nothing</a></li>
                        <li><a href="#">Submit to live</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Another Action</a></li>
                    </ul>
                </li>

                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-bell-o"></i>
                        <span class="notification">5</span>
                        <p class="hidden-md hidden-lg">
							Notifications
							<b class="caret"></b>
						</p>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Notification 1</a></li>
                        <li><a href="#">Notification 2</a></li>
                        <li><a href="#">Notification 3</a></li>
                        <li><a href="#">Notification 4</a></li>
                        <li><a href="#">Another notification</a></li>
                    </ul>
                </li>

                <li class="dropdown dropdown-with-icons">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-list"></i>
                        <p class="hidden-md hidden-lg">
							More
							<b class="caret"></b>
						</p>
                    </a>
                    <ul class="dropdown-menu dropdown-with-icons">
                        <li>
                            <a href="#">
                                <i class="pe-7s-mail"></i> Messages
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="pe-7s-help1"></i> Help Center
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="pe-7s-tools"></i> Settings
                            </a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">
                                <i class="pe-7s-lock"></i> Lock Screen
                            </a>
                        </li>
                        <li>
                            <a href="#" class="text-danger">
                                <i class="pe-7s-close-circle"></i>
                                Log out
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
        </div>
    </div>
</nav>

resources/views/layer/master.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="../assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Light Bootstrap Dashboard PRO by Creative Tim</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
    <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" />

    <!--  Light Bootstrap Dashboard core CSS    -->
    <link href="{{ asset('css/light-bootstrap-dashboard.css') }}" rel="stylesheet"/>



    <!--     Fonts and icons     -->
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <link href='{{ asset('css/font.css') }}' rel='stylesheet' type='text/css'>

</head>
<body>

<div class="wrapper">
    @include('layer.menu')
        <!--

            Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
            Tip 2: you can also add an image using data-image tag

        -->

        

    <div class="main-panel">
        @include('layer.header')


        <div class="main-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-10 col-md-offset-1">

                        <div class="card card-calendar">
                            <div class="content">
                               @yield('body')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

       @include('layer.footer')


    </div>
</div>


</body>
    <!--   Core JS Files  -->
    <script src="{{ asset('js/jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/bootstrap.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/perfect-scrollbar.jquery.min.js') }}" type="text/javascript"></script>
    <script src="{{ asset('js/light-bootstrap-dashboard.js') }}" type="text/javascript"></script>


</html>

resources/views/login.blade.php
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

	<title>Light Bootstrap Dashboard PRO by Creative Tim</title>

	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <!-- Bootstrap core CSS     -->
     <link href="{{ asset('css/bootstrap.min.css') }}" rel="stylesheet" />

    <!--  Light Bootstrap Dashboard core CSS    -->
    <link href="{{ asset('css/light-bootstrap-dashboard.css') }}" rel="stylesheet"/>



    <!--     Fonts and icons     -->
    <link href="{{ asset('css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/font.css') }}" rel='stylesheet' type='text/css'>
    
</head>
<body>



<div class="wrapper wrapper-full-page">
    <div class="full-page login-page" data-color="orange">

    <!--   you can change the color of the filter page using: data-color="blue | azure | green | orange | red | purple" -->
        <div class="content">
            <div class="container">
                <div class="row">
                    <div class="col-md-4 col-sm-6 col-md-offset-4 col-sm-offset-3">
                        <form method="post" action="{{ route('process_login') }}">
                        {{csrf_field()}}
                        
                        <!--   if you want to have the card without animation please remove the ".card-hidden" class   -->
                            <div class="card">
                                <div class="header text-center">Login</div>
                                <div class="content">
                                    @if (Session::has('error'))
                                        <h1>{{Session::get('error')}}</h1>
                                    @endif
                                    @if (Session::has('success'))
                                        <h1>{{Session::get('success')}}</h1>
                                    @endif
                                    <div class="form-group">
                                        <label>Email address</label>
                                        <input type="email" name="email" placeholder="Enter email" class="form-control">
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input type="password" name="mat_khau" placeholder="Password" class="form-control">
                                    </div>
                                </div>
                                <div class="footer text-center">
                                    <button type="submit" class="btn btn-fill btn-warning btn-wd">Login</button>
                                </div>
                            </div>

                        </form>

                    </div>
                </div>
            </div>
        </div>

    </div>

</div>


</body>

</html>

resources/views/muc_luong/view_all.blade.php
@extends('layer.master')
@section('body')
<a href="{{ route('muc_luong.view_insert') }}"> Thêm</a>
<table border="1" width="100%">
	<tr>
		<th>
			Mã
		</th>
		<th>
			Số Tiền Trên Một Giờ
		</th>
		<th>
			Sửa
		</th>
	</tr>
	@foreach($array as $each)
	<tr>
		<td>
			{{$each->ma_muc_luong}}
		</td>
		<td>
			{{$each->so_tien_tren_1_gio}}
		</td>
		<td>
				<a href="{{ route('muc_luong.view_update',['ma_muc_luong' => $each->ma_muc_luong]) }}">
					<button>Sửa</button>
				</a>
			</td>
	</tr>

	@endforeach
</table>
@endsection

resources/views/muc_luong/view_insert.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form action="{{ route('muc_luong.process_insert') }}" method="post">
		{{csrf_field()}}
		Số Tiền Trên Một Giờ
		<input type="number" name="so_tien_tren_1_gio">
		<br>
		<button>Thêm</button>
	</form>

</body>
</html>

resources/views/muc_luong/view_update.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
	<form action="{{ route('muc_luong.process_update',['ma_muc_luong' => $each->ma_muc_luong]) }}" method="post">
		{{csrf_field()}}
		Số Tiền Trên Một Giờ
		<input type="number" name="so_tien_tren_1_gio" value="{{$each->so_tien_tren_1_gio}}">
		<br>
		<button>Sửa</button>
	</form>

</body>
</html>